### ISSUE TITLE
Updates per oauth2-server-php changes

### ISSUE THREAD

**Issue by nerdfiles** [onassar/PHP-StripeOAuth#3]
https://github.com/bshaffer/oauth2-server-php implements the final draft of OAuth 2.0. I'm noticing issues particularly in https://github.com/nerdfiles/stripe-market/blob/master/includes/stripe-functions.php#L96-L974 when double usage of $_GET['code'] for the purposes of crafting tokens and public keys — specifically keys.

When it comes to Stripe, I'm attempting to Connect Accounts via OAuth2.0 ``authorization_code``s — accounts are being connected by it seems a double registration then queues up the deletion of that account. I have a feeling the culpable code exists here in the glue between oauth2-server-php and stripe-php itself.

**Comment by onassar** [comment]
Thanks for the feedback @nerdfiles  
Lil confused, though: how can I help?

**Comment by nerdfiles** [comment]
I'm doing [this](https://github.com/nerdfiles/stripe-market/compare/f1a86cd4a6fa...dc1d9f9ecdc6#diff-0e11e826f9f73b9c0203789070b8cd9aR159) — it would be helpful to know if this is going in the right direction.

**Comment by nerdfiles** [comment]
Given's Stripe's recent documentation, this is kind of outside of scope for my interests. But I've just been wondering. Perhaps this issue can be close if it's not really essential, and the core functionality is still available without updating to oauth2-server-php.

**Comment by onassar** [comment]
Gotcha. Not sure I can help really  
What is the "issue" that you've opened this ticket for?

**Comment by onassar** [comment]
Going to close this issue. Reopen if you have any questions.
